# QTERMWIDGET_BUILD_DIR="$PWD/../build" sip-build

# https://www.riverbankcomputing.com/static/Docs/sip/index.html

[build-system]
requires = ["sip", "PyQt-builder", "setuptools-scm"]
build-backend = "sipbuild.api"

[tool.sip.metadata]
name = "QTermWidget"
version = "1.0.0"

[tool.setuptools_scm]
